/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CartRouteImport } from './routes/cart'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as AccountDetailsRouteImport } from './routes/account.details'
import { Route as AccountDownloadsRouteImport } from './routes/account.downloads'
import { Route as BrandsIndexRouteImport } from './routes/brands.index'
import { Route as BrandsSlugRouteImport } from './routes/brands.$slug'
import { Route as CheckoutIndexRouteImport } from './routes/checkout.index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as AccountOrdersIndexRouteImport } from './routes/account.orders.index'
import { Route as AccountOrdersOrderRouteImport } from './routes/account.orders.$order'
import { Route as BrandsSlugIndexRouteImport } from './routes/brands.$slug.index'
import { Route as BrandsSlugProductsRouteImport } from './routes/brands.$slug.products'
import { Route as CheckoutConfirmationOrderRouteImport } from './routes/checkout.confirmation.$order'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountDetailsRoute = AccountDetailsRouteImport.update({
  id: '/account/details',
  path: '/account/details',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountDownloadsRoute = AccountDownloadsRouteImport.update({
  id: '/account/downloads',
  path: '/account/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsIndexRoute = BrandsIndexRouteImport.update({
  id: '/brands/',
  path: '/brands/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsSlugRoute = BrandsSlugRouteImport.update({
  id: '/brands/$slug',
  path: '/brands/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountOrdersIndexRoute = AccountOrdersIndexRouteImport.update({
  id: '/account/orders/',
  path: '/account/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountOrdersOrderRoute = AccountOrdersOrderRouteImport.update({
  id: '/account/orders/$order',
  path: '/account/orders/$order',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsSlugIndexRoute = BrandsSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BrandsSlugRoute,
} as any)
const BrandsSlugProductsRoute = BrandsSlugProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => BrandsSlugRoute,
} as any)
const CheckoutConfirmationOrderRoute =
  CheckoutConfirmationOrderRouteImport.update({
    id: '/checkout/confirmation/$order',
    path: '/checkout/confirmation/$order',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/legal': typeof LegalRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/account/details': typeof AccountDetailsRoute
  '/account/downloads': typeof AccountDownloadsRoute
  '/brands/$slug': typeof BrandsSlugRouteWithChildren
  '/products/$slug': typeof ProductsSlugRoute
  '/account/': typeof AccountIndexRoute
  '/brands/': typeof BrandsIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/account/orders/$order': typeof AccountOrdersOrderRoute
  '/brands/$slug/products': typeof BrandsSlugProductsRoute
  '/checkout/confirmation/$order': typeof CheckoutConfirmationOrderRoute
  '/account/orders/': typeof AccountOrdersIndexRoute
  '/brands/$slug/': typeof BrandsSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/legal': typeof LegalRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/account/details': typeof AccountDetailsRoute
  '/account/downloads': typeof AccountDownloadsRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/account': typeof AccountIndexRoute
  '/brands': typeof BrandsIndexRoute
  '/checkout': typeof CheckoutIndexRoute
  '/products': typeof ProductsIndexRoute
  '/account/orders/$order': typeof AccountOrdersOrderRoute
  '/brands/$slug/products': typeof BrandsSlugProductsRoute
  '/checkout/confirmation/$order': typeof CheckoutConfirmationOrderRoute
  '/account/orders': typeof AccountOrdersIndexRoute
  '/brands/$slug': typeof BrandsSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/legal': typeof LegalRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/account/details': typeof AccountDetailsRoute
  '/account/downloads': typeof AccountDownloadsRoute
  '/brands/$slug': typeof BrandsSlugRouteWithChildren
  '/products/$slug': typeof ProductsSlugRoute
  '/account/': typeof AccountIndexRoute
  '/brands/': typeof BrandsIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/account/orders/$order': typeof AccountOrdersOrderRoute
  '/brands/$slug/products': typeof BrandsSlugProductsRoute
  '/checkout/confirmation/$order': typeof CheckoutConfirmationOrderRoute
  '/account/orders/': typeof AccountOrdersIndexRoute
  '/brands/$slug/': typeof BrandsSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cart'
    | '/legal'
    | '/privacy'
    | '/search'
    | '/support'
    | '/terms'
    | '/account/details'
    | '/account/downloads'
    | '/brands/$slug'
    | '/products/$slug'
    | '/account/'
    | '/brands/'
    | '/checkout/'
    | '/products/'
    | '/account/orders/$order'
    | '/brands/$slug/products'
    | '/checkout/confirmation/$order'
    | '/account/orders/'
    | '/brands/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/legal'
    | '/privacy'
    | '/search'
    | '/support'
    | '/terms'
    | '/account/details'
    | '/account/downloads'
    | '/products/$slug'
    | '/account'
    | '/brands'
    | '/checkout'
    | '/products'
    | '/account/orders/$order'
    | '/brands/$slug/products'
    | '/checkout/confirmation/$order'
    | '/account/orders'
    | '/brands/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cart'
    | '/legal'
    | '/privacy'
    | '/search'
    | '/support'
    | '/terms'
    | '/account/details'
    | '/account/downloads'
    | '/brands/$slug'
    | '/products/$slug'
    | '/account/'
    | '/brands/'
    | '/checkout/'
    | '/products/'
    | '/account/orders/$order'
    | '/brands/$slug/products'
    | '/checkout/confirmation/$order'
    | '/account/orders/'
    | '/brands/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CartRoute: typeof CartRoute
  LegalRoute: typeof LegalRoute
  PrivacyRoute: typeof PrivacyRoute
  SearchRoute: typeof SearchRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  AccountDetailsRoute: typeof AccountDetailsRoute
  AccountDownloadsRoute: typeof AccountDownloadsRoute
  BrandsSlugRoute: typeof BrandsSlugRouteWithChildren
  ProductsSlugRoute: typeof ProductsSlugRoute
  AccountIndexRoute: typeof AccountIndexRoute
  BrandsIndexRoute: typeof BrandsIndexRoute
  CheckoutIndexRoute: typeof CheckoutIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  AccountOrdersOrderRoute: typeof AccountOrdersOrderRoute
  CheckoutConfirmationOrderRoute: typeof CheckoutConfirmationOrderRoute
  AccountOrdersIndexRoute: typeof AccountOrdersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/details': {
      id: '/account/details'
      path: '/account/details'
      fullPath: '/account/details'
      preLoaderRoute: typeof AccountDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/downloads': {
      id: '/account/downloads'
      path: '/account/downloads'
      fullPath: '/account/downloads'
      preLoaderRoute: typeof AccountDownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/': {
      id: '/brands/'
      path: '/brands'
      fullPath: '/brands/'
      preLoaderRoute: typeof BrandsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/$slug': {
      id: '/brands/$slug'
      path: '/brands/$slug'
      fullPath: '/brands/$slug'
      preLoaderRoute: typeof BrandsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/checkout'
      fullPath: '/checkout/'
      preLoaderRoute: typeof CheckoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/orders/': {
      id: '/account/orders/'
      path: '/account/orders'
      fullPath: '/account/orders/'
      preLoaderRoute: typeof AccountOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/orders/$order': {
      id: '/account/orders/$order'
      path: '/account/orders/$order'
      fullPath: '/account/orders/$order'
      preLoaderRoute: typeof AccountOrdersOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/$slug/': {
      id: '/brands/$slug/'
      path: '/'
      fullPath: '/brands/$slug/'
      preLoaderRoute: typeof BrandsSlugIndexRouteImport
      parentRoute: typeof BrandsSlugRoute
    }
    '/brands/$slug/products': {
      id: '/brands/$slug/products'
      path: '/products'
      fullPath: '/brands/$slug/products'
      preLoaderRoute: typeof BrandsSlugProductsRouteImport
      parentRoute: typeof BrandsSlugRoute
    }
    '/checkout/confirmation/$order': {
      id: '/checkout/confirmation/$order'
      path: '/checkout/confirmation/$order'
      fullPath: '/checkout/confirmation/$order'
      preLoaderRoute: typeof CheckoutConfirmationOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BrandsSlugRouteChildren {
  BrandsSlugProductsRoute: typeof BrandsSlugProductsRoute
  BrandsSlugIndexRoute: typeof BrandsSlugIndexRoute
}

const BrandsSlugRouteChildren: BrandsSlugRouteChildren = {
  BrandsSlugProductsRoute: BrandsSlugProductsRoute,
  BrandsSlugIndexRoute: BrandsSlugIndexRoute,
}

const BrandsSlugRouteWithChildren = BrandsSlugRoute._addFileChildren(
  BrandsSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CartRoute: CartRoute,
  LegalRoute: LegalRoute,
  PrivacyRoute: PrivacyRoute,
  SearchRoute: SearchRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  AccountDetailsRoute: AccountDetailsRoute,
  AccountDownloadsRoute: AccountDownloadsRoute,
  BrandsSlugRoute: BrandsSlugRouteWithChildren,
  ProductsSlugRoute: ProductsSlugRoute,
  AccountIndexRoute: AccountIndexRoute,
  BrandsIndexRoute: BrandsIndexRoute,
  CheckoutIndexRoute: CheckoutIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  AccountOrdersOrderRoute: AccountOrdersOrderRoute,
  CheckoutConfirmationOrderRoute: CheckoutConfirmationOrderRoute,
  AccountOrdersIndexRoute: AccountOrdersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
